# Generated by Django 4.1.1 on 2022-11-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='img',
            field=models.URLField(),
        ),
    ]
