# Generated by Django 4.1.1 on 2022-11-30 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_trait_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='img',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='rarity',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trait',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='trait',
            name='value',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
