# Generated by Django 4.1.1 on 2022-12-05 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_trait_img_alter_trait_rarity_alter_trait_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='rarity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trait',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
