# Generated by Django 4.1.1 on 2022-12-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_trait_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='rarity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
